language: scala
scala:
  - 2.10.2
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - mvn scm:checkout
  - cd morph
  - mvn scm:checkout
  - cd JSON-java
  - mvn clean install
  - cd ..
  - mvn clean install
  - cd ..
after_success:
  - wget https://raw.githubusercontent.com/stucco/test/master/rerun-test.sh
  - chmod a+x ./rerun-test.sh
  - ./rerun-test.sh